### ISSUE TITLE
Use `IsType` assertions in test

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#1570]
Using `IsType` is more expressive.
```suggestion
	node := initAndStartNodeWithCleanup(ctx, t, "full")
	require.IsType(t, new(FullNode), node)
```

_Originally posted by @tzdybal in https://github.com/rollkit/rollkit/pull/1544#discussion_r1504818159_
See also: https://github.com/rollkit/rollkit/pull/1544#discussion_r1504829123

**Comment by mttchrry** [comment]
Can you Assign this to me @tzdybal?

**Comment by PrathyushaLakkireddy** [comment]
@tzdybal I would like to work on this issue, Thank you.

**Comment by AryanGodara** [comment]
@tzdybal I was thinking that initially,
I had put assertions like `assert.NotNill(fn)` to verify the returned object from the helper function.
But then discussed it with Matthew and came to the conclusion that helper functions (in this case, `initAndStartNodeWithCleanup`) need to be robust, and in the current state, instead of propagating an error, or returning `nil`, they simply `panic`.

So, is there a need to check the type of the return value, if the program is going to panic beforehand anways, if something goes wrong?

I'm just curious about this one 😅

**Comment by tzdybal** [comment]
The only reason why I suggested this change is readability. When I first saw this code I was really confused - why type assertion is used when result is discarded anyways? Why there is no error check (second variable)? It was not obvious that this code ensures that returned object is of expected type.

Switching to (not adding :wink:)  `require.IsType` make the intention of the code obvious. This code is way more expressive and still holds all the same assumptions (it will stop if something goes wrong).

**Comment by AryanGodara** [comment]
> The only reason why I suggested this change is readability. When I first saw this code I was really confused - why type assertion is used when result is discarded anyways? Why there is no error check (second variable)? It was not obvious that this code ensures that returned object is of expected type.
> 
> Switching to (not adding 😉) `require.IsType` make the intention of the code obvious. This code is way more expressive and still holds all the same assumptions (it will stop if something goes wrong).

Aha, I see! You're right, the code did look confusing in the previous state 😅 
Learning new practices everyday :D
