### ISSUE TITLE
Add unit tests for `conv/abci` package

### ISSUE THREAD

**Issue by tzdybal** [rollkit/rollkit#283]
Functions in `conv/abci` package are very important to ensure compatibility with ABCI.
They should be tested extensively.

**Comment by omritoptix** [comment]
I'd like to join the effort by starting with this issue

**Comment by tzdybal** [comment]
Great! Feel free to ask any questions!

**Comment by omritoptix** [comment]
Currently it seems like the current conversion to ABCI block should not pass `ValidateBasic` of the ABCI block since the `DataHash` and `EvidenceHash` are being set from the optimint Block and not calculated from designated Hash functions (i.e `Data.Hash()` and `Evidence.Hash()`) Unlike the `LastCommitHash` which is being calculated by the optimint block using the ABCI block `LastCommit.Hash()`.

Not sure if it's currently by design, me missing something or it was simply a missed implementation detail. 

IMO this makes writing comprehensive tests harder since I think it’s important that besides making sure the conversion is yielding the expected result, the expected result should also pass the ValidateBasic of the ABCI block.
