### ISSUE TITLE
failed to write block header to header store error="header/store: non-adjacent: head 1,

### ISSUE THREAD

**Issue by zekchan** [rollkit/rollkit#908]
I run simpliest cosmos-sdk rollup, and after restarting aggregator node I see that logs:
```
5:46PM INF indexed block height=124 module=txindex
5:46PM INF Creating and publishing block height=125 module=BlockManager
5:46PM INF minted coins from module account amount=617931528515492647stake from=mint module=x/bank
5:46PM INF submitting block to DA layer height=125 module=BlockManager
5:47PM INF successfully submitted Rollkit block to DA layer daHeight=343576 module=BlockManager rollkitHeight=125
5:47PM INF commit synced commit=436F6D6D697449447B5B3631203735203135382033322031362037372031302031383420313532203931203134203133332031323120313837203230352037302031353020313332203131322038392031363620323520313637203138203230352032323720313520313832203433203233342036352031345D3A37447D
5:47PM ERR failed to write block header to header store error="header/store: non-adjacent: head 1, attempted 125" module=HeaderExchangeService
```

I restarted aggregator node with original --rollkit.da_start_height, with actual --rollkit.da_start_height and error is the same. New blocks are produced and sended to DA.
After restart of aggregator, my non-aggregator node connected to same  namespace stops sync every time. 
So question is - what is the one right way to stop and restart rollup? 
Should I use actual or inital da_start_height on aggregator?
How non-aggregator nodes knows which block asking from DA after aggregator downtime?
How to fix that error?

**Comment by jcstein** [comment]
hi @zekchan which version of rollkit are you on for this?

**Comment by gupadhyaya** [comment]
the header exchange service error reported by @zekchan should be fixed by https://github.com/rollkit/rollkit/pull/962 and look out for the next rollkit release which will include this fix.

when you restart your aggregator, you could point to latest DA height. e.g., which can be obtained as `DA_BLOCK_HEIGHT=$(curl http://0.0.0.0:26657/block | jq -r '.result.block.header.height')`, where 26657 is the port of your celestia-node. However, even if you start at an older DA height, it should not throw any error and should be able to pick up from where it was stopped.

**Comment by gupadhyaya** [comment]
we can close these two issues after #962 gets into next rollkit release
