### ISSUE TITLE
Error when starting node

### ISSUE THREAD

**Issue by samtvlabs** [rollkit/rollkit#976]
## Description

I am trying to run this [tutorial](https://rollkit.dev/docs/tutorials/gm-world/) and running into error when i run `./init-local.sh `

```shell
9:27AM ERR failed to retrieve block from DALC daHeight=164 errors="failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found; failed to retrieve block: getter/store: failed to retrieve shares by namespace: data not found" module=BlockManager
```

I would appreciate any guidance on this

**Comment by Manav-Aggarwal** [comment]
Hey @samtvlabs, it's possible the block was not posted yet by the aggregator before it tries to retrieve it. I think for a centralized sequencer scheme, we could even modify the code to remove the aggregator from trying to retrieve from the DA layer since there's no point trying to retrieve something it has already posted.

That said, we recently updated the gm tutorial in https://github.com/rollkit/docs/pull/247 and this issue should be resolved. Feel free to try it again.

**Comment by Manav-Aggarwal** [comment]
Feel free to reopen this if it persists.
